// CREATE name, age, rollno, marks as "test234";
// SHOW *;
// INSERT INTO "test234" VALUES ("Helllo", "WORLD", "10", "1000"), ("WORLD", "Hello", "11", "1002");
// INSERT INTO "test234" (name, age) VALUES ("Helllo", "WORLD"), ("WORLD", "Hello");
// TRUNCATE "test234";
// DELETE "test234";

// CREATE name, matches, runs, wickets as "Cricketers";

// INSERT INTO "Cricketers" (name, matches)
// VALUES
// ("Virat Kohli", "600"),
// ("Viv Richars", "370"),
// ("Anil Kumble", "256");

// Select * from "Crickters";